2018-08-12 10:19:34,102 ERROR: Exception on /index [GET] [in /home/jordy/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/media/jordy/Science/Programs/Web/Flask/microblog/app/routes.py", line 24, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/media/jordy/Science/Programs/Web/Flask/microblog/app/templates/index.html", line 9, in template
    {{ form.post.(cols=32, rows=4) }} <br>
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 667, in parse_postfix
    node = self.parse_subscript(node)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 700, in parse_subscript
    self.fail('expected name or number', attr_token.lineno)
  File "/home/jordy/anaconda3/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected name or number
